"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ThumbsUp, ThumbsDown, Copy, Check, FileText } from "lucide-react";

interface MessageActionsProps {
  content: string;
  onFeedback?: (type: 'up' | 'down') => void;
  onGeneratePDF?: () => void;
  showPDFButton?: boolean;
}

export default function MessageActions({
  content,
  onFeedback,
  onGeneratePDF,
  showPDFButton = true,
}: MessageActionsProps) {
  const [copied, setCopied] = useState(false);
  const [feedback, setFeedback] = useState<'up' | 'down' | null>(null);
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleFeedback = (type: 'up' | 'down') => {
    setFeedback(type);
    onFeedback?.(type);
    
    // Store feedback in localStorage for future improvements
    const feedbackData = {
      content: content.slice(0, 200),
      type,
      timestamp: Date.now(),
    };
    
    const existing = JSON.parse(localStorage.getItem('message_feedback') || '[]');
    localStorage.setItem('message_feedback', JSON.stringify([...existing, feedbackData]));
  };

  const handleGeneratePDF = async () => {
    setIsGeneratingPDF(true);
    
    try {
      // Create a new window with formatted content for printing/PDF
      const printWindow = window.open('', '_blank');
      if (!printWindow) {
        alert('Please allow popups to generate PDF');
        return;
      }

      const html = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>Koda-A Response</title>
          <style>
            @media print {
              body { print-color-adjust: exact; -webkit-print-color-adjust: exact; }
            }
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif;
              padding: 40px;
              line-height: 1.6;
              color: #333;
              max-width: 800px;
              margin: 0 auto;
            }
            h1 {
              color: #00bcd4;
              border-bottom: 2px solid #00bcd4;
              padding-bottom: 10px;
              font-size: 24px;
            }
            .content {
              margin-top: 20px;
              white-space: pre-wrap;
            }
            code {
              background: #f4f4f4;
              padding: 2px 6px;
              border-radius: 4px;
              font-family: 'Consolas', 'Monaco', monospace;
              font-size: 14px;
            }
            pre {
              background: #f4f4f4;
              padding: 15px;
              border-radius: 8px;
              overflow-x: auto;
              font-family: 'Consolas', 'Monaco', monospace;
              font-size: 14px;
              line-height: 1.5;
            }
            .footer {
              margin-top: 40px;
              font-size: 12px;
              color: #666;
              border-top: 1px solid #ddd;
              padding-top: 20px;
            }
            .print-button {
              position: fixed;
              top: 20px;
              right: 20px;
              padding: 10px 20px;
              background: #00bcd4;
              color: white;
              border: none;
              border-radius: 6px;
              cursor: pointer;
              font-size: 14px;
              font-weight: 500;
            }
            .print-button:hover {
              background: #00a5bb;
            }
            @media print {
              .print-button { display: none; }
            }
          </style>
        </head>
        <body>
          <button class="print-button" onclick="window.print()">🖨️ Print / Save as PDF</button>
          <h1>Koda-A Response</h1>
          <div class="content">${content
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/```([\s\S]*?)```/g, '<pre>$1</pre>')
            .replace(/`([^`]+)`/g, '<code>$1</code>')
            .replace(/\n/g, '<br>')}</div>
          <div class="footer">
            Generated by Koda-A on ${new Date().toLocaleString()}
          </div>
          <script>
            // Auto-open print dialog after a short delay
            setTimeout(() => {
              // Check if user wants to print
              if (confirm('Ready to generate PDF? Click OK to open print dialog.')) {
                window.print();
              }
            }, 500);
          </script>
        </body>
        </html>
      `;

      printWindow.document.write(html);
      printWindow.document.close();
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Failed to generate PDF. Please try again.');
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  return (
    <div className="flex items-center gap-1 mt-2 opacity-0 group-hover:opacity-100 transition-opacity">
      {/* Copy Button */}
      <motion.button
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        onClick={handleCopy}
        className="p-1.5 rounded-lg text-gray-500 hover:text-gray-300 hover:bg-white/5 transition-colors"
        title="Copy message"
      >
        <AnimatePresence mode="wait">
          {copied ? (
            <motion.div
              key="check"
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              exit={{ scale: 0 }}
            >
              <Check size={14} className="text-green-400" />
            </motion.div>
          ) : (
            <motion.div
              key="copy"
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              exit={{ scale: 0 }}
            >
              <Copy size={14} />
            </motion.div>
          )}
        </AnimatePresence>
      </motion.button>

      {/* Thumbs Up */}
      <motion.button
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        onClick={() => handleFeedback('up')}
        className={`p-1.5 rounded-lg transition-colors ${
          feedback === 'up'
            ? 'text-green-400 bg-green-400/10'
            : 'text-gray-500 hover:text-gray-300 hover:bg-white/5'
        }`}
        title="Good response"
      >
        <ThumbsUp size={14} fill={feedback === 'up' ? 'currentColor' : 'none'} />
      </motion.button>

      {/* Thumbs Down */}
      <motion.button
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        onClick={() => handleFeedback('down')}
        className={`p-1.5 rounded-lg transition-colors ${
          feedback === 'down'
            ? 'text-red-400 bg-red-400/10'
            : 'text-gray-500 hover:text-gray-300 hover:bg-white/5'
        }`}
        title="Bad response"
      >
        <ThumbsDown size={14} fill={feedback === 'down' ? 'currentColor' : 'none'} />
      </motion.button>

      {/* Generate PDF Button */}
      {showPDFButton && (
        <motion.button
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          onClick={handleGeneratePDF}
          disabled={isGeneratingPDF}
          className="p-1.5 rounded-lg text-gray-500 hover:text-blue-400 hover:bg-blue-400/10 transition-colors disabled:opacity-50"
          title="Export as PDF"
        >
          {isGeneratingPDF ? (
            <div className="w-3.5 h-3.5 border-2 border-current border-t-transparent rounded-full animate-spin" />
          ) : (
            <FileText size={14} />
          )}
        </motion.button>
      )}
    </div>
  );
}
